### PR TITLE
Push tomviz forward

### PR DESCRIPTION
**Pull request by cjh1**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cjh1** [comment]
@conda-forge-admin please rerender

**Comment by cjh1** [comment]
@mrakitin Can I get a review on this? Thanks.

**Review by mrakitin — APPROVED** [review]
Looks good to me, @cjh1! I updated the mismatched hash for OpenChemistry. Hopefully, it runs successfully now.

**Comment by cjh1** [comment]
@mrakitin Thanks, looks like we now have a dependence conflict any ideas?

**Comment by mrakitin** [comment]
@cjh1, yes, looks like there are some missing packages for Python 3.9 only, as the other builds for Python 3.6-3.8 passed.

The last successful build we had was https://github.com/conda-forge/tomviz-feedstock/commit/afc4d02555271a41c495d636528ef0351e8f6885, that was only for Python 3.7. I think we can exclude Python 3.9 cases for now, and create an issue to try it later once more dependency packages are built for Python 3.9.

**Comment by cjh1** [comment]
@mrakitin I thought we were only building for [3.7](https://github.com/conda-forge/tomviz-feedstock/blob/master/recipe/conda_build_config.yaml)? Should the exclude be done another way?

**Pull request merged**
