### PR TITLE
Bump to latest master

### PR DESCRIPTION
**Pull request by cjh1**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cjh1** [comment]
@conda-forge-admin, please rerender

**Comment by cjh1** [comment]
@cryos If we can get this approved, we should have a new package by tomorrow.

**Comment by cryos** [comment]
Looks great to me, thanks for your work on this @cjh1

**Review by mrakitin — APPROVED** [review]
Looks good to me, thanks @cjh1!

**Pull request merged**
