### PR TITLE
Bump to latest master

### PR DESCRIPTION
**Pull request by cjh1**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cjh1** [comment]
@conda-forge-admin, please rerender

**Comment by cjh1** [comment]
@mrakitin @psavery I have raise this separate PR just to resolve the current build issue and avoid confusion with the `itk-elastix` discussion. We can also install `itk-elastix` with pip in the conda environment if necessary.

**Comment by cjh1** [comment]
@mrakitin Just confirming we see the same issue here. Can you give an example of how to roll back to centos 6 ?

**Comment by mrakitin** [comment]
> @mrakitin Just confirming we see the same issue here. Can you give an example of how to roll back to centos 6 ?

Create a file `recipe/conda_build_config.yaml` and the needed version in this section from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/ccb80c0817dfe616fbc081010b957b3383d1e010/recipe/conda_build_config.yaml#L141-L150.

**Comment by cjh1** [comment]
@mrakitin Thanks, I will give it a go.

**Comment by cjh1** [comment]
@mrakitin That didn't seem to help.

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by cjh1** [comment]
@conda-forge-admin, please rerender.

**Review by mrakitin — APPROVED** [review]
Looks good to me! That seemed to successfully pick up the older image:
image

**Comment by cjh1** [comment]
@mrakitin Thanks your help!

**Pull request merged**
